/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package URL;

import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
/**
 *
 * @author ASUS
 */
public class GUIURL extends javax.swing.JFrame {
    Controller controller;
    /**
     * Creates new form GUIURL
     */
    public GUIURL() {
        initComponents();
        controller = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtURL = new javax.swing.JLabel();
        inputURL = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        txtHasil = new javax.swing.JLabel();
        txtJdul = new javax.swing.JLabel();
        output_judul = new javax.swing.JTextField();
        txtKeyword = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output_keyword = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Output_deskripsi = new javax.swing.JTextArea();
        txtTampilan = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tampil_halaman = new javax.swing.JEditorPane();
        txtIsi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Output_isi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("GUI URL");

        txtURL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtURL.setText("Masukkan URL");

        inputURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputURLActionPerformed(evt);
            }
        });

        btnInput.setBackground(new java.awt.Color(255, 255, 255));
        btnInput.setText("INPUT");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        txtHasil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtHasil.setText("Hasil Pencarian");

        txtJdul.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtJdul.setText("Judul Halaman");

        output_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                output_judulActionPerformed(evt);
            }
        });

        txtKeyword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtKeyword.setText("Keyword");

        Output_keyword.setColumns(20);
        Output_keyword.setRows(5);
        jScrollPane1.setViewportView(Output_keyword);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Deskripsi");

        Output_deskripsi.setColumns(20);
        Output_deskripsi.setRows(5);
        jScrollPane3.setViewportView(Output_deskripsi);

        txtTampilan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtTampilan.setText("Tampilan Halaman");

        jScrollPane4.setViewportView(tampil_halaman);

        txtIsi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtIsi.setText("Isi Konten");

        Output_isi.setColumns(20);
        Output_isi.setRows(5);
        jScrollPane2.setViewportView(Output_isi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKeyword)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(output_judul, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputURL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnInput))
                                    .addComponent(txtJdul)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTampilan)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIsi))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURL)
                    .addComponent(txtTampilan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJdul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(output_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(txtKeyword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputURLActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputActionPerformed

    private void output_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_output_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_output_judulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIURL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIURL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIURL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIURL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIURL().setVisible(true);
            }
        });
    }
    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public JTextArea getOutput_isi() {
        return Output_isi;
    }

    public void setOutput_isi(JTextArea Output_isi) {
        this.Output_isi = Output_isi;
    }

    public JTextArea getOutput_keyword() {
        return Output_keyword;
    }

    public void setOutput_keyword(JTextArea Output_keyword) {
        this.Output_keyword = Output_keyword;
    }

    public JButton getBtnInput() {
        return btnInput;
    }

    public void setBtnInput(JButton btnInput) {
        this.btnInput = btnInput;
    }

    public JTextField getInputURL() {
        return inputURL;
    }

    public void setInputURL(JTextField inputURL) {
        this.inputURL = inputURL;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTextField getOutput_judul() {
        return output_judul;
    }

    public void setOutput_judul(JTextField output_judul) {
        this.output_judul = output_judul;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JEditorPane getTampil_halaman() {
        return tampil_halaman;
    }

    public void setTampil_halaman(JEditorPane tampil_halaman) {
        this.tampil_halaman = tampil_halaman;
    }

    public JLabel getTxtHasil() {
        return txtHasil;
    }

    public void setTxtHasil(JLabel txtHasil) {
        this.txtHasil = txtHasil;
    }

    public JLabel getTxtIsi() {
        return txtIsi;
    }

    public void setTxtIsi(JLabel txtIsi) {
        this.txtIsi = txtIsi;
    }

    public JLabel getTxtJdul() {
        return txtJdul;
    }

    public void setTxtJdul(JLabel txtJdul) {
        this.txtJdul = txtJdul;
    }

    public JLabel getTxtKeyword() {
        return txtKeyword;
    }

    public void setTxtKeyword(JLabel txtKeyword) {
        this.txtKeyword = txtKeyword;
    }

    public JLabel getTxtTampilan() {
        return txtTampilan;
    }

    public void setTxtTampilan(JLabel txtTampilan) {
        this.txtTampilan = txtTampilan;
    }

    public JLabel getTxtURL() {
        return txtURL;
    }

    public void setTxtURL(JLabel txtURL) {
        this.txtURL = txtURL;
    }

    public JTextArea getOutput_deskripsi() {
        return Output_deskripsi;
    }

    public void setOutput_deskripsi(JTextArea Output_deskripsi) {
        this.Output_deskripsi = Output_deskripsi;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Output_deskripsi;
    private javax.swing.JTextArea Output_isi;
    private javax.swing.JTextArea Output_keyword;
    private javax.swing.JButton btnInput;
    private javax.swing.JTextField inputURL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField output_judul;
    private javax.swing.JEditorPane tampil_halaman;
    private javax.swing.JLabel txtHasil;
    private javax.swing.JLabel txtIsi;
    private javax.swing.JLabel txtJdul;
    private javax.swing.JLabel txtKeyword;
    private javax.swing.JLabel txtTampilan;
    private javax.swing.JLabel txtURL;
    // End of variables declaration//GEN-END:variables
}
